# Generated by Django 4.0.2 on 2022-02-24 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('phoneNumber', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('accountBalance', models.IntegerField()),
                ('reviews', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='workersReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('description', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerWR', to='moneyLawndering.user')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workerWR', to='moneyLawndering.user')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('time_est', models.FloatField()),
                ('dayOfWeek', models.CharField(max_length=10)),
                ('startTimeOfDay', models.FloatField()),
                ('endTimeOfDay', models.FloatField()),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('status', models.IntegerField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerListing', to='moneyLawndering.user')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workerListing', to='moneyLawndering.user')),
            ],
        ),
        migrations.CreateModel(
            name='customersReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('description', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerCR', to='moneyLawndering.user')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workerCR', to='moneyLawndering.user')),
            ],
        ),
        migrations.CreateModel(
            name='AppliedFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerAppliedFor', to='moneyLawndering.user')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workerAppliedFor', to='moneyLawndering.user')),
            ],
        ),
    ]
