# Generated by Django 4.0.2 on 2022-02-24 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneyLawndering', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='pub_date',
            new_name='pubDate',
        ),
    ]
