# Generated by Django 4.0.2 on 2022-02-24 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneyLawndering', '0002_rename_pub_date_listing_pubdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customersReviews',
            new_name='CustomerReview',
        ),
        migrations.RenameModel(
            old_name='workersReviews',
            new_name='WorkerReview',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='reviews',
            new_name='rating',
        ),
    ]
