# Generated by Django 4.0.2 on 2022-03-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyLawndering', '0003_rename_customersreviews_customerreview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(),
        ),
    ]
