# Generated by Django 4.0.2 on 2022-03-14 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneyLawndering', '0004_alter_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedfor',
            name='customer',
        ),
        migrations.AddField(
            model_name='appliedfor',
            name='listing',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, related_name='listingAppliedFor', to='moneyLawndering.listing'),
        ),
        migrations.AlterField(
            model_name='user',
            name='accountBalance',
            field=models.FloatField(),
        ),
    ]
