# Generated by Django 4.0.2 on 2022-03-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyLawndering', '0006_alter_listing_dayofweek_alter_listing_endtimeofday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='worker',
            field=models.IntegerField(),
        ),
    ]
