# Generated by Django 4.0.2 on 2022-03-15 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneyLawndering', '0007_alter_listing_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedfor',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneyLawndering.listing'),
        ),
        migrations.AlterField(
            model_name='appliedfor',
            name='worker',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customerreview',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneyLawndering.user'),
        ),
        migrations.AlterField(
            model_name='customerreview',
            name='worker',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneyLawndering.user'),
        ),
        migrations.AlterField(
            model_name='workerreview',
            name='customer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workerreview',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneyLawndering.user'),
        ),
    ]
