# Generated by Django 3.2.7 on 2022-03-15 22:08

from django.db import migrations
from django.utils import timezone

def users(apps, schema_editor):
    User = apps.get_model('moneyLawndering', 'User')
    worker = User(name= 'john', email= 'john@gmail.com',type= 0, password= 'john', phoneNumber= 8015555555, address= '105 John Ln.', accountBalance= 278, rating= 5)
    worker.save()
    customer = User(name = 'tim', email = 'tim@gmail.com',type = 1, password = 'tim', phoneNumber = 4355555555, address = '105 Tim Ln.', accountBalance = 278, rating = 5)
    customer.save()
    admin = User(name = 'admin', email = 'admin@gmail.com',type = 2, password = 'admin', phoneNumber = 2135555555, address = '105 Admin Ln.', accountBalance = 278, rating = 5)
    admin.save()

def listing(apps, schema_editor):
    User = apps.get_model('moneyLawndering', 'User')
    Listing = apps.get_model('moneyLawndering', 'Listing')
    customer = User.objects.get(pk=2)
    listing = customer.listing_set.create(category = 'Lawn Mowing', location = '105 Tim Ln.', time_est = 1, dayOfWeek = 'monday', startTimeOfDay = '13:15', endTimeOfDay = '14:15', description = 'Mow my Lawn', price = 25, status = 1, worker = 0, pubDate = timezone.now())
    listing.save()

def category(apps, schema_editor):
    Category = apps.get_model('moneyLawndering', 'Category')
    category = Category(type = 'Lawn Mowing')
    category = category.save()

class Migration(migrations.Migration):

    dependencies = [
        ('moneyLawndering', '0009_alter_appliedfor_listing'),
    ]

    operations = [
        migrations.RunPython(users),
        migrations.RunPython(listing),
        migrations.RunPython(category),
    ]
