# Generated by Django 3.2.7 on 2022-03-15 22:08

from django.db import migrations
from django.utils import timezone

def users(apps, schema_editor):
    User = apps.get_model('moneyLawndering', 'User')

    admin = User(name='admin', email='admin@gmail.com', type=2, password='admin', phoneNumber=7012616515, address='105 Admin Lane', accountBalance=278, rating=5)
    admin.save()

    customer1 = User(name='Amie Z.', email='amie@gmail.com', type=1, password='amie', phoneNumber=4322045298, address='223 Tim Lane', accountBalance=558, rating=5)
    customer1.save()
    customer2 = User(name='Brad Y.', email='brad@gmail.com', type=1, password='brad', phoneNumber=8035944973, address='3041 Java Lane', accountBalance=108, rating=4)
    customer2.save()
    customer3 = User(name='Christie X.', email='christie@gmail.com', type=1, password='christie', phoneNumber=4103068046, address='3680 Blue Spruce Lane', accountBalance=209, rating=2)
    customer3.save()
    customer4 = User(name='Dan W.', email='dan@gmail.com', type=1, password='dan', phoneNumber=8106716633, address='550 Perry Street', accountBalance=1000, rating=1)
    customer4.save()
    customer5 = User(name='Elaine V.', email='elaine@gmail.com', type=1, password='elaine', phoneNumber=4402849525, address='2768 Ralph Drive', accountBalance=34, rating=5)
    customer5.save()
    customer6 = User(name='Fred U.', email='fred@gmail.com', type=1, password='fred', phoneNumber=3309015655, address='3920 Horner Street', accountBalance=56, rating=3)
    customer6.save()
    customer7 = User(name='Grace T.', email='grace@gmail.com', type=1, password='grace', phoneNumber=7244736777, address='3080 Shinn Avenue', accountBalance=13, rating=4)
    customer7.save()
    customer8 = User(name='Harry S.', email='harry@gmail.com', type=1, password='harry', phoneNumber=5619660174, address='592 Pleasant Hill Road', accountBalance=86, rating=5)
    customer8.save()
    customer9 = User(name='Iona R.', email='iona@gmail.com', type=1, password='iona', phoneNumber=8589431202, address='984 Carson Street', accountBalance=48, rating=2)
    customer9.save()
    customer10 = User(name='John Q.', email='john@gmail.com', type=1, password='john', phoneNumber=6168639179, address='1946 Kimberly Way', accountBalance=130, rating=4)
    customer10.save()

    worker1 = User(name='Krystal P.', email= 'krystal@gmail.com',type= 0, password= 'krystal', phoneNumber= 8177300639, address= '2784 Moore Avenue', accountBalance=20, rating=1)
    worker1.save()
    worker2 = User(name='Larry O.', email='larry@gmail.com', type=0, password='larry', phoneNumber=7012793947, address='306 Catherine Drive', accountBalance=13, rating=5)
    worker2.save()
    worker3 = User(name='Monica N.', email='monica@gmail.com', type=0, password='monica', phoneNumber=8453534141, address='2796 Benedum Drive', accountBalance=0, rating=3)
    worker3.save()
    worker4 = User(name='Ned M.', email='ned@gmail.com', type=0, password='ned', phoneNumber=6629973676, address='4388 Flint Street', accountBalance=19, rating=2)
    worker4.save()
    worker5 = User(name='Opal L.', email='opal@gmail.com', type=0, password='opal', phoneNumber=3183559882, address='1075 Roguski Road', accountBalance=0, rating=4)
    worker5.save()
    worker6 = User(name='Pete K.', email='pete@gmail.com', type=0, password='pete', phoneNumber=7273471958, address='3545 Badger Pond Lane', accountBalance=25, rating=5)
    worker6.save()
    worker7 = User(name='Queenie J.', email='queenie@gmail.com', type=0, password='queenie', phoneNumber=9095281814, address='4998 Gordon Street', accountBalance=34, rating=5)
    worker7.save()
    worker8 = User(name='Ryan I.', email='ryan@gmail.com', type=0, password='ryan', phoneNumber=9254933556, address='1350 Park Street', accountBalance=0, rating=2)
    worker8.save()
    worker9 = User(name='Sofia H.', email='sofia@gmail.com', type=0, password='sofia', phoneNumber=4154281466, address='389 Roosevelt Street', accountBalance=108, rating=4)
    worker9.save()
    worker10 = User(name='Tyler G.', email='tyler@gmail.com', type=0, password='tyler', phoneNumber=3202955719, address='2084 Newton Street', accountBalance=15, rating=4)
    worker10.save()

def listing(apps, schema_editor):
    User = apps.get_model('moneyLawndering', 'User')
    Listing = apps.get_model('moneyLawndering', 'Listing')

    customer1 = User.objects.get(pk=2)
    listing1 = customer1.listing_set.create(category='Lawn Mowing', location='84321', time_est=2, dayOfWeek='saturday', startTimeOfDay='10:00', endTimeOfDay='14:30', description='Mow my Lawn', price=25, status=0, worker=0, pubDate=timezone.now())
    listing1.save()
    listing2 = customer1.listing_set.create(category='Car Wash', location='84321', time_est=1, dayOfWeek='wednesday', startTimeOfDay='12:00', endTimeOfDay='17:30', description='There\'s sand at the bottom of my pool that I want gone.', price=15, status=0, worker=0, pubDate=timezone.now())
    listing2.save()
    listing3 = customer1.listing_set.create(category='Lawn Mowing', location='84321', time_est=2, dayOfWeek='saturday', startTimeOfDay='10:00', endTimeOfDay='14:30', description='Mow my Lawn', price=25, status=0, worker=0, pubDate=timezone.now())
    listing3.save()
    listing4 = customer1.listing_set.create(category='Car Wash', location='84321', time_est=1, dayOfWeek='friday', startTimeOfDay='15:00', endTimeOfDay='16:30', description='I need my car washed before my date Friday night.', price=15, status=0, worker=0, pubDate=timezone.now())
    listing4.save()
    listing5 = customer1.listing_set.create(category='Gardening & Weeding', location='84321', time_est=3, dayOfWeek='tuesday', startTimeOfDay='16:00', endTimeOfDay='18:30', description='These weeds are springing up like crazy!', price=40, status=0, worker=0, pubDate=timezone.now())
    listing5.save()
    listing6 = customer1.listing_set.create(category='Lawn Mowing', location='84321', time_est=2, dayOfWeek='saturday', startTimeOfDay='10:00', endTimeOfDay='14:30', description='Mow my Lawn', price=25, status=0, worker=0, pubDate=timezone.now())
    listing6.save()
    listing7 = customer1.listing_set.create(category='Pruning', location='84321', time_est=1, dayOfWeek='monday', startTimeOfDay='10:00', endTimeOfDay='14:30', description='The branches on my tree are too wild! Help!', price=35, status=0, worker=0, pubDate=timezone.now())
    listing7.save()
    listing8 = customer1.listing_set.create(category='Lawn Mowing', location='84321', time_est=2, dayOfWeek='saturday', startTimeOfDay='10:00', endTimeOfDay='14:30', description='Mow my Lawn', price=25, status=0, worker=0, pubDate=timezone.now())
    listing8.save()
    listing9 = customer1.listing_set.create(category='Car Wash', location='84321', time_est=1, dayOfWeek='friday', startTimeOfDay='15:00', endTimeOfDay='16:30', description='I need my car washed before my date Friday night.', price=15, status=0, worker=0, pubDate=timezone.now())
    listing9.save()

    customer2 = User.objects.get(pk=3)
    listing10 = customer2.listing_set.create(category='Spring Cleanup', location='84322', time_est=4, dayOfWeek='saturday', startTimeOfDay='9:00', endTimeOfDay='17:30', description='It\'s that time of year again! I need help cleaning up my yard.', price=50, status=0, worker=0, pubDate=timezone.now())
    listing10.save()
    listing11 = customer2.listing_set.create(category='Pruning', location='84322', time_est=2, dayOfWeek='thursday', startTimeOfDay='9:15', endTimeOfDay='17:45', description='I need my fruit trees pruned!', price=45, status=0, worker=0, pubDate=timezone.now())
    listing11.save()

    customer3 = User.objects.get(pk=4)
    listing12 = customer3.listing_set.create(category='Branch and Leaf Removal', location='84341', time_est=2, dayOfWeek='Sunday', startTimeOfDay='12:30', endTimeOfDay='17:45', description='I have some sticks all over my yard that I\'d like cleaned up!', price=20, status=0, worker=0, pubDate=timezone.now())
    listing12.save()

def category(apps, schema_editor):
    Category = apps.get_model('moneyLawndering', 'Category')
    category1 = Category(type='Lawn Mowing')
    category1.save()
    category2 = Category(type='Pruning')
    category2.save()
    category3 = Category(type='Spring Cleanup')
    category3.save()
    category4 = Category(type='Branch & Leaf Removal')
    category4.save()
    category5 = Category(type='Gardening & Weeding')
    category5.save()
    category6 = Category(type='Car Wash')
    category6.save()
    category7 = Category(type='Pool Maintenance')
    category7.save()


class Migration(migrations.Migration):

    dependencies = [
        ('moneyLawndering', '0009_alter_appliedfor_listing'),
    ]

    operations = [
        migrations.RunPython(users),
        migrations.RunPython(listing),
        migrations.RunPython(category),
    ]
