# Generated by Django 4.0.2 on 2022-03-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyLawndering', '0010_auto_20220315_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='workername',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
