# Generated by Django 4.0.2 on 2022-04-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyLawndering', '0011_listing_workername'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='workerPhoneNumber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
